# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 5  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ee_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_interfaces:
      - position
ee_group_controller:
  ros__parameters:
    joints:
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position