## MoveIt properties
move_group_name:  arm_group
joint_limit_margins: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]  # added as a buffer to joint limits [radians or meters]. If moving quickly, make this larger.
command_out_topic: /arm_group_controller/joint_trajectory