# Configuration file for eRob actuator
vendor_id: 0x5a65726f
product_id: 0x00029252
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: true  # true = automatic fault reset
rpdo:  # RxPDO 
  - index: 0x1600
    channels:
      - {index: 0x607A, sub_index: 0, type: int32, command_interface: position, default: .nan} # Target Position
      - {index: 0x60FE, sub_index: 0, type: uint32}   # Digital Outputs
      - {index: 0x6040, sub_index: 0, type: uint16}      # Control Word
tpdo:  # TxPDO
  - index: 0x1A00
    channels:
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position} # Position Actual Value
      - {index: 0x60FD, sub_index: 0, type: uint32}       # Digital Inputs
      - {index: 0x6041, sub_index: 0, type: uint16}         # Status Word
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}